# This workflow will run publish a package to GitHub Packages when a release is created
# Tests, build and version bump should be done before.

name: Node.js Package

on:
    release:
        types: [created]

jobs:

    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
